### ISSUE TITLE
T3S\T3sJslidernews\ViewHelpers\LinkViewHelper - problem

### ISSUE THREAD

**Issue by konstantin83** [subugoe/typo3-t3sjslidernews#1]
Hi,
Receiving this error after page reload:
`Uncaught TYPO3 Exception
#1: PHP Catchable Fatal Error: Argument 1 passed to T3S\T3sJslidernews\ViewHelpers\LinkViewHelper::render() must be an instance of Tx_News_Domain_Model_News, instance of GeorgRinger\News\Domain\Model\NewsDefault given in /var/www/html/typo3conf/ext/t3s_jslidernews/Classes/ViewHelpers/LinkViewHelper.php line 93

TYPO3\CMS\Core\Error\Exception thrown in file
/var/www/typo3_src-6.2.14/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 101.`

Frontend renders slider well, and then after browser refresh is throws this error. Insteresting fact - if you clear all caches, it renders well again but only one time, then error again.

Take a look into `typo3conf/ext/t3s_jslidernews/Classes/ViewHelpers/LinkViewHelper.php` and didn't find mensions of `GeorgRinger\News\Domain\Model\NewsDefault` at all.
What seems to be the problem?

**Comment by ipf** [comment]
Hi, there are different problems ;)

The most important one is, that this extension is not developed here. It was just put here because we had to fix a few things. You should use the one from TER.

The issue that happened to you is, that tx_news has namespaced its PHP code and the `Tx_News_Domain_Model_News` is the legacy non-up-to-date version of a class that is now called `GeorgRinger\News\Domain\Model\NewsDefault`. So - either your news version is too new, the slider extension is too old, or the slider author didn't adopt his code to the namespaces in news.
